id: P61EB2313
initial_creation_type: input
source_metadata:
  title: Rinchen Terdzö Series
  language: zh
  description: 'Texts belonging to (and related to) the Rinchen Terdzö (rin chen gter
    mdzod) or Precious Treasury of Revelations, one of the five treasuries of Jamgön
    Kongtrul Lodrö Thayé (1813–1899). Note that the volume numbers below correspond
    to the Shechen Publications edition (2007–2008):'
  volume:
    5d6b1f82848543559a27745aa72276c4:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Volume 1
    2bca3b809f3d42ffaf6e7f68e2fbfc66:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Volume 1
    163c8759285543688b23a566e7e5f728:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Volume 1
    56974ab82ae546e995c1ed64bb28d4a8:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Volume 1
    d8a37523f98b449ba19d9fe4482ec1df:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Volume 1
    bf9852407fc145d9825fd90acdf40216:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Volume 1
    4a0a04f341604ab98ae4f524651711a4:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Volume 1
    7db97e6d3e9244929d719e38f9e924e4:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Volume 1
    2137f56427c04d9ca6760330a4bc9069:
      title: The Lament of Rudra
      parent: Volume 5
    ee879212e70d43c5b4915d47f69e4ccc:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Volume 5
    49810bc0e28e4796a764642ebf5e02d9:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Volume 5
    82c3363572884d00b463f4d4059150fd:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Volume 5
    4acee6f3fea746f29a17332b33b18ebf:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Volume 5
    6b695dc139c144ef844ba0d942e51cde:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Volume 5
    265d2de49bf2404186ce030eeb7b966c:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Volume 5
    2d0c9cd584da450fa8f5fc9fccf51bf2:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Volume 5
    d66ef8314ff84c2bbc3553d6fd826046:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Volume 6
    2e8915f5c75049698dd4173018142f76:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Volume 10
    531f51b3d4d245058e464d7b6ccb426b:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Volume 10
    1335576352ed4bfdb79042c4b2067ad4:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Volume 10
    f92954a3463c4a6092f16df985b7a2d8:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Volume 10
    655af354c4dd45b382cabcd37b2a28a6:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Volume 10
    cf7ef27d0f9d4b199303d0362c60ac3f:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Volume 10
    e591f283265349a9806a1afe1f467546:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Volume 10
    cf735edcf86445f3bdd27af7771e0681:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Volume 11
    2c222b7dca49453a948e39c6fb92b582:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Volume 11
    eae2caeaf77d4ff6912e69219072cf49:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Volume 11
    22eb0b3efab64157b9c01e17e38da984:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Volume 11
    cb461a28180f45e28f0ba3a5ef5ec468:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Volume 16
    b116e2e807ac49608b7a05554f6e40cc:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Volume 16
    8cb4596e546d4ee5bc6dd2c13e374435:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Volume 21
    2160899b055a4561925c7adf26d5b2c5:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Volume 22
    bbc4f961cf464ee897f1bdd07f8305e7:
      title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural
        Transmission
      parent: Volume 26
    353f0949fe0e4129ae3fb0b63ad2356f:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Volume 31
    9613ae451f5f41ce9211f819afcd5b23:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: Volume 32
    d56d02e514584d4eb0d6e0f507d3dfb5:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Volume 36
    7f938aac1d1e43d4a67047537229188e:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Volume 36
    c5c67f171e994dd482cd7b0794a96815:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Volume 36
    7fc0a3ca414149719dbaae3920a7ac1a:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Volume 36
    2a991fa92644450f96347c0d4aeb3d8d:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Volume 36
    30a7655f5a8d4342ae3bc5decc9cf622:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Volume 36
    f3c3a38ca7b845879bcd741411cbf7da:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Volume 36
    d8e87cf4b8e14dbea3b312e90e5e0e2d:
      title: The Twenty-Eight Commitments
      parent: Volume 41
    5e6790d5da384202b36c13e1fbdd666c:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Volume 41
    722aadec58dc4ae08d7e1a88ac7a05b7:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Volume 41
    937d5bad0c494230b1542f07bb0c7faf:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Volume 41
    a4e84eb15bc241d69964eef6e1e1e288:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Volume 41
    6e86d8b98324449eb547d4c3cb038e15:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      parent: Volume 41
    30855c4788a94882bafe039170b26ea4:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: Volume 41
    fc69eb3db53e47f981cc986dd1e6ae6b:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Volume 42
    c35af9299a8c45a7af9561fa8a4b0031:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Volume 42
    f56c8a1390894811b7cb88a488b7b394:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Volume 42
    411457ae305b453197ea0e41f3bebeb4:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Volume 43
    236d27a7827545ef85dbd0161e877ad9:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Volume 43
    1af13964d5034cb89db520ca2ba360e4:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Volume 45
    3283a08266f14867a8684d67fe342b17:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Volume 47
    adce586d363f460bb52df9d1584058fd:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Volume 48
    9d24428fde9e41979200bd15a921f4cf:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Volume 48
    77dce12f535b4e3799a1e0d675aa4351:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Volume 48
    e04bd94860774f859dc8405c4efd73bb:
      title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of
        Abhirati'
      parent: Volume 48
    faf84b892658474ca7f1a6ea559b8055:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Volume 49
    8158ff8155a641ae99d3d0dca0c547b7:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Volume 49
    19e5ad2335a1441abcdd690d110dfa3c:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Volume 49
    059c016118474af2affb99ddfe7ac9b6:
      title: Prayer for the Future of the Dharma
      parent: Volume 52
    bb45cc72c3944fe29ae585944b1a41fa:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Volume 52
    52a46e15c61e40139c291792bc10e47f:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Volume 52
    a0c2ab0b171c4068a0887e684b394ba8:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Volume 52
    eaecef6bad204436aafc4775871cb61c:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Volume 60
    4b2d4ab63b0f4120896a7fe3fb5b4240:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Volume 60
    2ec024ac20c84920b889c98c895280cd:
      title: The Pointing-the-Staff Instruction
      parent: Volume 60
    7ba77f95c29747558ba00e6e3274c2af:
      title: Yeshe Tsogyal's Prayer
      parent: Volume 60
    1c6fbf0a731a45a9a8adb86b2c3958b4:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Volume 60
    286e01a2f8d44fa4b34c827717109253:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Volume 65
    7d7732a38b3d41a9ad922b8137bce179:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Volume 67
created_at: '2022-03-01T05:31:39.705573'
last_modified_at: '2022-03-01T05:31:39.705575'
